name: CustomGravity
main: me.shadow5353.customgravity.CustomGravity
version: 0.4.1
description: Change your gravity with commands
author: shadow5353
softdepend: [Vault]

commands:
    customgravity:
        usage: /<command>
        description: main command
        aliases: [cg]

permission:
    customgravity.*:
        description: Gives all permission to the plugin
        children:
            customgravity.1: op
            customgravity.2: op
            customgravity.3: op
            customgravity.4: op
            customgravity.5: op
            customgravity.0: op
            customgravity.-1: op
            customgravity.-2: op
            customgravity.-3: op
            customgravity.-4: op
            customgravity.-5: op
            customgravity.-6: op
            customgravity.gravity: op
            customgravity.remove: op
            customgravity.sign.create: op
            customgravity.sign.use.0: op
            customgravity.sign.use.1: op
            customgravity.sign.use.2: op
            customgravity.sign.use.3: op
            customgravity.sign.use.4: op
            customgravity.sign.use.5: op
            customgravity.sign.use.-1: op
            customgravity.sign.use.-2: op
            customgravity.sign.use.-3: op
            customgravity.sign.use.-4: op
            customgravity.sign.use.-5: op
            customgravity.admin: op
    customgravity.admin:
        description: Gives permission to all admin commands
        default: op
    customgravity.0:
        description: Gives permission to /cg 0
        default: op
    customgravity.1:
        description: Gives permission to /cg 1
        default: op
    customgravity.2:
        description: Gives permission to /cg 2
        default: op
    customgravity.3:
        description: Gives permission to /cg 3
        default: op
    customgravity.4:
        description: Gives permission to /cg 4
        default: op
    customgravity.5:
        description: Gives permission to /cg 5
        default: op
    customgravity.-1:
        description: Gives permission to /cg -1
        default: op
    customgravity.-2:
        description: Gives permission to /cg -2
        default: op
    customgravity.-3:
        description: Gives permission to /cg -3
        default: op
    customgravity.-4:
        description: Gives permission to /cg -4
        default: op
    customgravity.-5:
        description: Gives permission to /cg -5
        default: op
    customgravity.-6:
        description: Gives permission to /cg -6
        default: op
    customgravity.gravity:
        description: Gives permission to /cg gravity
        default: true
    customgravity.remove:
        description: Gives permission to /cg remove
        default: op
    customgravity.sign.use.0:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.1:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.2:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.3:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.4:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.5:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.-1:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.-2:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.-3:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.-4:
        description: Gives permission to use signs
        default: op
    customgravity.sign.use.-5:
        description: Gives permission to use signs
        default: op
    customgravity.sign.create:
        description: Gives permission to create all signs
        default: op
    customgravity.sign.remove:
        description: Gives permission to remove signs
        default: op